-- MySQL Script generated by MySQL Workbench
-- 04/21/21 19:40:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `idfuncionarios` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(145) NULL COMMENT '',
  `cpf` VARCHAR(45) NULL COMMENT '',
  `ativo` TINYINT(1) NULL COMMENT '',
  `contato` VARCHAR(45) NULL COMMENT '',
  `dataanscimento` VARCHAR(45) NULL COMMENT '',
  `rg` VARCHAR(45) NULL COMMENT '',
  `cargo` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idfuncionarios`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `senha` VARCHAR(245) NULL COMMENT '',
  `ativo` VARCHAR(45) NULL COMMENT '',
  `funcionarios_idfuncionarios` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idusuarios`)  COMMENT '',
  INDEX `fk_usuarios_funcionarios_idx` (`funcionarios_idfuncionarios` ASC)  COMMENT '',
  CONSTRAINT `fk_usuarios_funcionarios`
    FOREIGN KEY (`funcionarios_idfuncionarios`)
    REFERENCES `mydb`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `endereco_logradouro` VARCHAR(245) NULL COMMENT '',
  `endereco_numero` INT NULL COMMENT '',
  `endereco_bairro` VARCHAR(45) NULL COMMENT '',
  `endereco_referencia` VARCHAR(45) NULL COMMENT '',
  `data_nascimento` VARCHAR(45) NULL COMMENT '',
  `cpf` VARCHAR(45) NULL COMMENT '',
  `sexo` VARCHAR(45) NULL COMMENT '',
  `contato_tel` VARCHAR(45) NULL COMMENT '',
  `contato_email` VARCHAR(45) NULL COMMENT '',
  `ativo` TINYINT(1) NULL COMMENT '',
  `endereco_cep` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idclientes`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acessos` (
  `idacessos` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `data_hora_login` VARCHAR(45) NULL COMMENT '',
  `data_hora_logout` VARCHAR(45) NULL COMMENT '',
  `funcionarios_idfuncionarios` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idacessos`)  COMMENT '',
  INDEX `fk_acessos_funcionarios1_idx` (`funcionarios_idfuncionarios` ASC)  COMMENT '',
  CONSTRAINT `fk_acessos_funcionarios1`
    FOREIGN KEY (`funcionarios_idfuncionarios`)
    REFERENCES `mydb`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marcas` (
  `idmarcas` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `data_inclusao` VARCHAR(45) NULL COMMENT '',
  `ativo` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idmarcas`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedores` (
  `idfornecedores` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `endereco_logradouro` VARCHAR(45) NULL COMMENT '',
  `endereco_numero` INT NULL COMMENT '',
  `endereco_cep` VARCHAR(45) NULL COMMENT '',
  `endereco_bairro` VARCHAR(45) NULL COMMENT '',
  `contato_tel` VARCHAR(45) NULL COMMENT '',
  `contato_email` VARCHAR(45) NULL COMMENT '',
  `contato_tel2` VARCHAR(45) NULL COMMENT '',
  `cnpj` VARCHAR(45) NULL COMMENT '',
  `ativo` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idfornecedores`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `marcas_idmarcas` INT NOT NULL COMMENT '',
  `fornecedores_idfornecedores` INT NOT NULL COMMENT '',
  `tamanho` VARCHAR(45) NULL COMMENT '',
  `descricao` VARCHAR(245) NULL COMMENT '',
  `sexo` VARCHAR(45) NULL COMMENT '',
  `cor` VARCHAR(45) NULL COMMENT '',
  `ativo` TINYINT(1) NULL COMMENT '',
  `cod_barra` VARCHAR(45) NULL COMMENT '',
  `data_entrada` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idprodutos`)  COMMENT '',
  INDEX `fk_produtos_marcas1_idx` (`marcas_idmarcas` ASC)  COMMENT '',
  INDEX `fk_produtos_fornecedores1_idx` (`fornecedores_idfornecedores` ASC)  COMMENT '',
  CONSTRAINT `fk_produtos_marcas1`
    FOREIGN KEY (`marcas_idmarcas`)
    REFERENCES `mydb`.`marcas` (`idmarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_fornecedores1`
    FOREIGN KEY (`fornecedores_idfornecedores`)
    REFERENCES `mydb`.`fornecedores` (`idfornecedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendas` (
  `idvendas` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `data_hora` VARCHAR(45) NULL COMMENT '',
  `metodo_pagamento` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idvendas`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendas_has_produtos` (
  `vendas_idvendas` INT NOT NULL COMMENT '',
  `produtos_idprodutos` INT NOT NULL COMMENT '',
  PRIMARY KEY (`vendas_idvendas`, `produtos_idprodutos`)  COMMENT '',
  INDEX `fk_vendas_has_produtos_produtos1_idx` (`produtos_idprodutos` ASC)  COMMENT '',
  INDEX `fk_vendas_has_produtos_vendas1_idx` (`vendas_idvendas` ASC)  COMMENT '',
  CONSTRAINT `fk_vendas_has_produtos_vendas1`
    FOREIGN KEY (`vendas_idvendas`)
    REFERENCES `mydb`.`vendas` (`idvendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_has_produtos_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `mydb`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoques` (
  `idestoques` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `qtd` INT NULL COMMENT '',
  `data_chegada` VARCHAR(45) NULL COMMENT '',
  `ativo` TINYINT(1) NULL COMMENT '',
  `produtos_idprodutos` INT NOT NULL COMMENT '',
  `funcionarios_idfuncionarios` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idestoques`)  COMMENT '',
  INDEX `fk_estoques_produtos1_idx` (`produtos_idprodutos` ASC)  COMMENT '',
  INDEX `fk_estoques_funcionarios1_idx` (`funcionarios_idfuncionarios` ASC)  COMMENT '',
  CONSTRAINT `fk_estoques_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `mydb`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoques_funcionarios1`
    FOREIGN KEY (`funcionarios_idfuncionarios`)
    REFERENCES `mydb`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
